### ISSUE TITLE
Minor issue: PV Inverter doesn't show power, nor phases

### ISSUE THREAD

**Issue by kds69** [freakent/dbus-mqtt-devices#131]
### Version

0.8.0 (current)

### VenusOS version

3.50

### Does this issue occur during installation or at runtime ?

Runtime

### What is the issue you are actually experiencing?

Not sure this is a dbus-mqtt-service problem or a Venus OS problem.
Power per phases is not displayed on Venus monitor dashboard/overview. Instead it is shown as "undefined: 0W"
Btw, I suspect this is an issue since long, from v2.8x  already when I got started with my solar equipment I never management to get power per phases displayed though it is well reported in other screens (see below screen print). But it doesn't seems to cause any harm anyway, so more of cosmetic issue on new GUI where it appears in an obvious manner now:

![image](https://github.com/user-attachments/assets/f620552b-1c86-4b29-9cde-e80fd47ec982)

whereas:
![image](https://github.com/user-attachments/assets/2d7e73da-8a27-4a0b-a69d-bc3065454857)

...and thank you so much for all this fantastic job btw!!

**Comment by kds69** [comment]
what I wrote above is not fully correct: phases to show in the old gui, but on the alternative dashboard. see below:
![image](https://github.com/user-attachments/assets/9b5b3b15-7850-4d1b-9bd9-81da638de251)

**Comment by freakent** [comment]
Hi, you'll have to help me understand the screen shots better. The PV Inverter config was community provided so I've never used it myself. 

Is the "undefined" valued an attribute value that you send via mqtt or is it a derived value? The reason I ask is that it could be the attribute is not properly defined or missing in the settings.yaml file.

**Comment by freakent** [comment]
I don't have a value displayed under solar yield to know what should be displayed there. 

![image](https://github.com/user-attachments/assets/0bf63a77-c820-4623-8f59-2516608dfe7b)

**Comment by kds69** [comment]
Thanks for your quick reply!!
I think the issue is on Venus OS, not your driver, thus you can disregard and I'll check with the victron community rather.

I have a pv inverter connected to AC input of a Multiplus II. 
May I bet you have a mppt connected to your battery instead..(+a wind turbine or generator??)

**Comment by kds69** [comment]
this will is fixed in Venus beta 3.51:
[https://community.victronenergy.com/t/venus-os-beta-series-announcement-and-changelog-v3-51-2/10041/2](url)
