### ISSUE TITLE
Not working after updating Cerbo Firmware

### ISSUE THREAD

**Issue by pluto202** [freakent/dbus-mqtt-devices#133]
### Version

0.6.3

### VenusOS version

v3.4.2

### Does this issue occur during installation or at runtime ?

Runtime

### What is the issue you are actually experiencing?

I updated my Cerbo to the version v3.4.2. Afterwards my small additional inverter integrated via mqtt did not show up in the Venus console. I run the setup.sh again as noted in the readme file. Then the inverter appeared in the console but without any values. After troubleshooting I decided to uninstall dbus-mqtt-devices 0.6.3 and installed 0.8.0. Now everything is working again without issues.

Just for your information. System is working again. 

Thanks for your work!!!

### Relevant log output

```shell
I could not identify any related message in the log before I updated to 0.8.0.
```

**Comment by freakent** [comment]
Glad you got the latest version working.
