### ISSUE TITLE
Custom name missing after CCGX reboot

### ISSUE THREAD

**Issue by gharshaw** [freakent/dbus-mqtt-devices#15]
@freakent 
Hi Martin,
After further investigation, the re-registration is not overwriting the local /data/conf/settings.xml file after a reboot and a re-registration. The GUI shows the default name, again the settings.xml still has custom name. I have to re-enter the custom name in the GUI for it to take effect.

Thoughts?
Thanks,
Gene

**Comment by freakent** [comment]
Gene, can you provide the service type and the status message you are registering with?

**Comment by gharshaw** [comment]
Martin,

device/<nr001/Status
{
   "clientId": "nr001",
   "connected": 1,
   "version": "v2.3",
   "services": {
       "t1": "temperature",
       "t2": "temperature",
       "t3": "temperature",
       "t4": "temperature",
       "t5": "temperature",
       "tk1": "tank",
       "tk2": "tank",
       "tk3": "tank",
       "tk4": "tank" 
   } 
}

**Comment by freakent** [comment]
In the topic name you have <nr001, is that a typo?

**Comment by gharshaw** [comment]
Good eye :-)  the "<" in clientid was a typo -- I just fixed it in my topic. Retested - same outcome.
After reboot:
![image](https://user-images.githubusercontent.com/79295813/166979737-5ceb4b50-6d32-400b-baaf-2d0c143fcda9.png)
After reregister:
![image](https://user-images.githubusercontent.com/79295813/166979791-1b9ef041-b2d2-40f3-8c7f-9a0a197e36b0.png)
And my settings.xml

[settings.zip](https://github.com/freakent/dbus-mqtt-devices/files/8633373/settings.zip)

Thanks for the help!!

**Comment by freakent** [comment]
Seems like a regression error. I'll have to do more testing and create a fix.

**Comment by gharshaw** [comment]
Appreciate it!
Question: Does your service update the D-Bus or does a Victron Service? The reason I ask is that looking at Dbus-spy the Custom Name is populated with the "default" Custom name
![image](https://user-images.githubusercontent.com/79295813/167031395-d89435e1-7bad-4300-94fa-f3e3fad72248.png)

**Comment by freakent** [comment]
Victron provides a library called velib.

**Comment by freakent** [comment]
Fixed in release v0.5.1
