### ISSUE TITLE
Something is sending R/xxxxx/system/0/Serial all the time

### ISSUE THREAD

**Issue by Joeknx** [freakent/dbus-mqtt-devices#27]
Something is sending R/xxxxx/system/0/Serial all the time

an I get a lot of MQTT Messages with "#"

Before I installed "bus-mqtt-devices" I had only the keepalive payload items.

**Comment by freakent** [comment]
I don't believe this has anything to do with the driver itself. The driver does not publish to those topics.

**Comment by Joeknx** [comment]
Ok, I have to search somewhere else. 

It's just that I had the keepalive items been send, and now I have thousands of messages.
