### ISSUE TITLE
How to set up a second gridmeter?

### ISSUE THREAD

**Issue by Joeknx** [freakent/dbus-mqtt-devices#30]
To display the heatpump I would like to add a second gridmeter.
But if I add a second one, it is displayed with the first one. Only in the portal settings, I see the device.

**Comment by freakent** [comment]
You will have to supply sample code to demonstrate how you are using the driver. Remember, the driver just registers the device to the dbus, after that you are using Victron's standard dbus-Mqtt interface.

**Comment by Joeknx** [comment]
Ok thank you. The registration works. So I have to deal with the dbus interface.
