### ISSUE TITLE
Epever Solar Charger

### ISSUE THREAD

**Issue by DerRudi79** [freakent/dbus-mqtt-devices#34]
Moin,
ich hoffe das mir hier jemand eventuell auf deutsch weiter helfen kann ansonsten muss ich mit dem Übersetzer arbeiten. 
Ich möchte meine beiden Epever Laderegler mit in dem Venus OS integrieren.
Die Laderegler sind bereits mit einem anderen RaspberryPi verbunden und stellen alle Werte über MQTT zu Verfügung.
Ich habe dbus-mqtt-devices nach Anleitung installiert.
Ich verstehe nicht wie und wo ich die Geräte registrieren kann. Geht das alles über Node-RED? Kann mir jemand ein Beispiel Flow zur Verfügung stellen damit ich die Zusamenhänge verstehen kann und sehe wo ich was eintragen muss.

Vielen dank Rudi

**Comment by freakent** [comment]
Hi Rudi, I know a little German but still had to use translator...

There are a few folks using the driver with node-red. Perhaps, they can chime in.  I am also a big fan of node-red for other projects I support.

For this driver, the device registration is performed over mqtt. As I am sure you know, node-red has mqtt subscribe and publish nodes built in. Before sending your data to venus device, your node-red will need to send the "connect" message over mqtt. You will also need to subscribe to the topic for a response that will include the DeviceInstance id issued by VenusOS for your device. You will need this id to send/receive data via Victron's dbus-mqtt interface using node-red.  

I don't have a node-red example, but if you look in the test-data folder you will see simple examples in Python which should be easy to follow.
