### ISSUE TITLE
Energy Meter missing under settings

### ISSUE THREAD

**Issue by mtucker502** [freakent/dbus-mqtt-devices#41]
My energy meter is showing correctly under the normal device list:
<img width="494" alt="image" src="https://user-images.githubusercontent.com/5040678/219429246-1fc57407-e9b8-4cae-9530-d26184bcf9f8.png">

I can see all of the values as expected:
<img width="497" alt="image" src="https://user-images.githubusercontent.com/5040678/219429355-b71b145f-68b5-4f1d-9be0-f6e7654fb649.png">

But if I navigate to Settings > Energy Meters it's blank:
![image](https://user-images.githubusercontent.com/5040678/219429594-45d59c8a-b7ee-4660-9d2e-cb10ee8d2545.png)
![image](https://user-images.githubusercontent.com/5040678/219429654-bacbfdb0-39cb-445c-9e35-31be285c0ed4.png)

Is this an issue with my config or an expected behavior as the GX can't control or change any settings on my MQTT meter?

**Comment by freakent** [comment]
I assume that since your energy meter is custom that it's settings are under "My Grid Meter" not on Victron's Settings screen.

**Comment by stundenblume** [comment]
Even a "Victron" EM24 won't be listed there.
