### ISSUE TITLE
Setting up an LED charge indicator

### ISSUE THREAD

**Issue by stephwe** [freakent/dbus-mqtt-devices#45]
The Heidelberg Energy display is difficult to see. The ESP should still have a free pin. This could be used, for example, to control an LED NeoPixel Ring WS2812 with 32 LEDs as a charge indicator. Since 5V has to be placed in the box anyway, you could use the voltage as the power supply for the LED. A simple running light during the charging process would be enough.

**Comment by freakent** [comment]
Sorry, did you post this issue to the correct place? I don't see how this driver relates to your comment?
