### ISSUE TITLE
humidity 

### ISSUE THREAD

**Issue by tumekee** [freakent/dbus-mqtt-devices#46]
would appear that humidity is no longer and option ? was having a look at this https://github.com/victronenergy/venus/wiki/dbus#temperatures and appears they have closed it off to Ruvvie only ?

**Comment by tumekee** [comment]
sorry no it works... i was using W/<VRM ID>/temperature/1/Temperature &  W/<VRM ID>/Humidity/1/Humidity,  when it should just be W/<VRM ID>/temperature/1/Temperature W/<VRM ID>/temperature/1/Humidity

**Comment by freakent** [comment]
Glad you figured it out. There are some examples in the test-data folder. Is it just the formatting on here or do you have two slashes "/" after the W? There should only be a single slash.

**Comment by tumekee** [comment]
After much head bashing - yes ! $5 esp8622 + $40 hydrostatic sensor is much better than paying for the $200 victron tank sensor ! The VRM id goes between the // I added this in my comment but for some reason it won’t show up.
