### ISSUE TITLE
Temperature sensors not appearing in my VRM Device list

### ISSUE THREAD

**Issue by gharshaw** [freakent/dbus-mqtt-devices#47]
Is it just my account or should the temperature sensors be appearing in the VRM device list as they do show on the VRM dashboard?

**Comment by freakent** [comment]
Please case you provide more information and some screenshots?

**Comment by gharshaw** [comment]
My temp and tank sensors that are published to the dbus appear correctly on the VRM dashboard however only the tanks appear on the VRM device list.
![image](https://user-images.githubusercontent.com/79295813/223439973-ede10058-bd91-4301-bb78-d5453fc736ff.png)

![image](https://user-images.githubusercontent.com/79295813/223440027-feac431c-c5b9-4d14-8834-0672bd31550b.png)

I am unable to remove the temp sensors from VRM since they are not on the device list. 
I'm curious if this is the case for all using this device driver

Regards
Gene

**Comment by freakent** [comment]
You are correct. I just checked my test set up where I have ruuvi tags and a the temperature simulator running. The device list only shows the Ruuvi tags. 

![image](https://user-images.githubusercontent.com/124850/223449849-f9306e30-8bae-470f-94b2-479a26b24f3d.png)

![image](https://user-images.githubusercontent.com/124850/223450051-308c4980-9128-44f7-a6c2-84c43be573f1.png)


I'm not sure exactly why that is. There are some differences in the dbus values but I can't see anything obvious. I could be that VRM is explicityly looking for the name Ruuvi somewhere.

<img width="538" alt="image" src="https://user-images.githubusercontent.com/124850/223448526-847b0878-a835-4818-983a-ac96553eb803.png">

<img width="540" alt="image" src="https://user-images.githubusercontent.com/124850/223448959-de7aa2c3-0bac-4d06-8f7a-c77cfcfc83eb.png">

At the end of the day, I can't see that this is really that useful. You **should** be sending a disconnect (connect=0) with a Last Will message when the device disconnects from MQTT.  The GX device will then spot disconnected devices and give you the option of removing them.

**Comment by freakent** [comment]
dbus whilst devices are connected over MQTT

<img width="536" alt="image" src="https://user-images.githubusercontent.com/124850/223452256-4e3627df-13e7-4e88-8f7a-56b3343e1376.png">

dbus after devices have disconnected and Last Will message sent

<img width="537" alt="image" src="https://user-images.githubusercontent.com/124850/223452516-5caff117-44fb-4342-b909-537a3b2e26fc.png">

**Comment by gharshaw** [comment]
As you see in my screenshot my IN temp sensor states it has not updated in 5 days although it is updating on my CCGX. I think it might be corrupted in VRM. Do you think sending the last will message will remove it from VRM and on a new connection will recreate it on VRM?

**Comment by freakent** [comment]
I would use dbus-spy to see what is in the dbus. You might find it easier to clean up the dbus by hand.

But you should ensure you have a Last Will message set in your code.

**Comment by gharshaw** [comment]
I am using node-red. I just shut it down cleanly and it did not send a last will or disconnect. According to node-red documents it should have. Do you have any experience with the node-red mqtt nodes?

Regards

**Comment by freakent** [comment]
I do know NodeRed well (see my other popular project) although it's been a while so I have to rely on my memory. 

The last will message is sent by the client (in this case NodeRed) to the MQTT broker when the client **connects**. If the client disconnects unexpectedly then the **broker** sends the last will message to the topic it was intended for. 

There is a good article here:

http://stevesnoderedguide.com/configuring-the-mqtt-publish-node

Also take a look at the samples in the test-data folder. They are written in python but you should be able to understand the Mqtt last will set up.

**Comment by gharshaw** [comment]
Thanks for the additional info. I have the lastwill and disconnect working now by  updating  the close and will message configuration in  the NR MQTT broker config. After making this change and forcing a close it seems to have corrected the VRM update issue

![image](https://user-images.githubusercontent.com/79295813/223566581-aa9b2f04-3ca9-4a38-956b-4491c1ea07ae.png)
