### ISSUE TITLE
possible to add services like ac-charger and dc-system?

### ISSUE THREAD

**Issue by kr0815** [freakent/dbus-mqtt-devices#50]
I tuned my Victron ESS with
- an additional charger to load the batteries faster when there is much sun
- an additional small 300W-Inverter with better efficiency

No i want to have them in the Venus-GUI To get correct calculations of the house consumption

I guess i have to adapt services.yml?

Anybody did this before?

What is the right service to show up in the main GUI site - only very few are possible?

I think the best would be for my purpose a DC-System?

**Comment by stundenblume** [comment]
> an additional small 300W-Inverter with better efficiency

pvinverter is the right service


> an additional charger to load the batteries faster when there is much sun

https://github.com/victronenergy/venus/wiki/dbus#solar-chargers
or
https://github.com/victronenergy/venus/wiki/dbus#ac-chargers

Both are not defined in[ services.yml](https://github.com/freakent/dbus-mqtt-devices/blob/main/services.yml) right now but can be added easily .

**Comment by kr0815** [comment]
PVinverter would be AC, i think i need solarcharger?

But i don´t understand the whole system
Example- i try to fake a genset
it´s on DBus, i see it in Venus as a sensor, but i don´t see a Generator in the GUI?
Is there a special product ID needed?

![Zwischenablage03](https://user-images.githubusercontent.com/16240382/232342698-290d4678-54b2-4123-ae91-a2fe71c58437.jpg)
![Zwischenablage02](https://user-images.githubusercontent.com/16240382/232342716-0933eba0-c625-4615-99c2-01c15f09bb3a.jpg)
![Zwischenablage01](https://user-images.githubusercontent.com/16240382/232342730-35717288-a7bc-4957-9476-22ec9193b5d1.jpg)

**Comment by stundenblume** [comment]
With this driver I just have experience with pvinverter, gridmeter and temperature.

I think you already got it working and push data into the right MQTT topics, right?

The only thing missing is the display in VRM Portal?

**Comment by kr0815** [comment]
Yes, the Data is pushed in the right topic
I tried vith various programs, but never got it showed up in the GUI

My problem: if the additional Battery-connected inverter pushes 300W to the house, Venus doesn´t calculate with that for house consumption

I need to "fake" a PV-Charger like in the attached Picture

![Zwischenablage04](https://user-images.githubusercontent.com/16240382/232344250-4fa75808-2767-40f3-b0ad-0c493076fd04.jpg)

**Comment by stundenblume** [comment]
Than you have to define a [solar-charger](https://github.com/victronenergy/venus/wiki/dbus#solar-chargers) in [services.yml](https://github.com/freakent/dbus-mqtt-devices/blob/main/services.yml).
