### ISSUE TITLE
Display total solar is missing - Adding SMA Inverter

### ISSUE THREAD

**Issue by phoenix-83** [freakent/dbus-mqtt-devices#51]
Hello
I have a question about the integration of a SMA inverter.
It is a Tripower X 20-50, which is unfortunately not automatically detected by Venus OS. That is why I have inserted the values via mqtt.
This also works so far only the solar yield is not displayed in the VRM. The following (red marked) parts are missing:

![grafik](https://user-images.githubusercontent.com/95980470/234790537-bfb21e33-9ce7-4b33-a1da-e4b3fd8768a1.png)

First of all: I did not make any adjustments in the services.yml. 

Does anyone have an idea how I can include solar generation in the VRM portal?
Without the solar generation, unfortunately, the consumption values are not displayed correctly:
![grafik](https://user-images.githubusercontent.com/95980470/234786915-3338a144-15fd-4846-a860-d7e868f2ce44.png)

**Comment by stundenblume** [comment]
Is this the topic you are looking for?: `W/.../pvinverter/6/Ac/Energy/Forward`

**Comment by phoenix-83** [comment]
i hope this topic is correct. 
The current problem is that the firmware of the Tripower X does not yet provide this value via Modbus. Here a firmware update must take place first. let's see when this happens...

**Comment by stundenblume** [comment]
Maybe you can calculate it by yourself or use a different source?
Everything would be better than nothing.

**Comment by freakent** [comment]
As this isn't directly related to the driver I am going to close this issue now.
