### ISSUE TITLE
Venus Os Crash after add a PV Inverter

### ISSUE THREAD

**Issue by Jacke87** [freakent/dbus-mqtt-devices#60]
Hello after adding a PV Inverter to Venus OS on AC1 Out my System crash.
I use Venus OS 3.01 with louis dbus serial JKBms.
Both devices get the VRM instance 1. i don´t know if this is the problem.
my code worked for 3 mOnths untill yesterday. My SD Card was corrupted and i instal a fresh Venus an know i Have the issues.
![absturz](https://github.com/freakent/dbus-mqtt-devices/assets/101046051/383d07a4-7015-4163-b1fe-c4bfad10f570)
![menü alles da](https://github.com/freakent/dbus-mqtt-devices/assets/101046051/932c1ecf-5520-433a-96ad-3f8528affd38)

**Comment by freakent** [comment]
Hi, before we jump into this, lets check the basics. Have you run through the trouble shooting guide in the README? In particular check the log file at /var/log/dbus-mqtt-devices/current.

**Comment by Jacke87** [comment]
this is the log file
`@4000000064e632c10bc217fc INFO:device_manager:Using portalId XXXXXXXXXX
@4000000064e632c308619b64 INFO:mqtt_gobject_bridge:[Init] Connecting to local broker
@4000000064e632c30cba5aac INFO:device_manager:[Connected] Result code 0
@4000000064e633b5045f4d04 ERROR:mqtt_gobject_bridge:[Disconnected] Lost connection to broker
@4000000064e633b5045f608c INFO:mqtt_gobject_bridge:[Disconnected] Set timer
@4000000064e633ba0474099c INFO:mqtt_gobject_bridge:[Reconnect] start
@4000000064e633ba04c1a0e4 INFO:mqtt_gobject_bridge:[Reconnect] success
@4000000064e633ba04e5c2e4 INFO:device_manager:[Connected] Result code 0
@4000000064e633bf19a8cf3c INFO:device_manager:Received device status message {'clientId': 'fe001', 'connected': 1, 'version': 'v1.0 ALPHA', 'services': {'t1': 'temperature'}}
@4000000064e633bf1a1227fc INFO:device:**** Registering device: fe001, services: {'t1': 'temperature'} ****
@4000000064e633bf1a26a9fc INFO:device:Registering Service temperature for client fe001
@4000000064e633bf1a40c97c INFO:device_service_config:About to open config file
@4000000064e633c00eee6534 INFO:device_service:Registering service temperature for client fe001 at path com.victronenergy.temperature.mqtt_fe001_t1
@4000000064e633c011884ddc INFO:settingsdevice:Setting /Settings/Devices/mqtt_fe001_t1/ClassAndVrmInstance does not exist yet or must be adjusted
@4000000064e633c015c6a754 INFO:vedbus:registered ourselves on D-Bus as com.victronenergy.temperature.mqtt_fe001_t1
@4000000064e633c01647c604 INFO:device_service:Registered Service com.victronenergy.temperature.mqtt_fe001_t1 under DeviceInstance 1
@4000000064e633c016594294 INFO:device_manager:publish {'portalId': 'XXXXXXXXXX', 'deviceInstance': {'t1': '1'}} to device/fe001/DBus, status is 0
@4000000064e633c016de5ccc INFO:device_manager:Received device status message {'clientId': 'Growatt', 'connected': 0, 'version': 'v1.0 ALPHA', 'services': {'wr': 'pvinverter'}}
@4000000064e633c016ed83b4 WARNING:device_manager:tried to remove device Growatt that is not registered
@4000000064e633c0172364ac INFO:device_manager:Received device status message {'clientId': 'fe001', 'connected': 1, 'version': 'v1.0 ALPHA', 'services': {'t1': 'temperature'}}
@4000000064e633c0174ada3c INFO:device_manager:publish {'portalId': 'XXXXXXXXXX', 'deviceInstance': {'t1': '1'}} to device/fe001/DBus, status is 0
@4000000064e633c0176abe4c INFO:device_manager:Received device status message {'clientId': 'cb001', 'connected': 0, 'version': 'v1', 'services': {'Aquarium': 'grid'}}
@4000000064e633c0177539e4 WARNING:device_manager:tried to remove device cb001 that is not registered
@4000000064e633c017a21a2c INFO:device_manager:Received device status message {'clientId': 'cb002', 'connected': 1, 'version': 'v1', 'services': {'Growatt': 'pvinverter'}}
@4000000064e633c017ac7684 INFO:device:**** Registering device: cb002, services: {'Growatt': 'pvinverter'} ****
@4000000064e633c017b42f14 INFO:device:Registering Service pvinverter for client cb002
@4000000064e633c017bc1684 INFO:device_service_config:About to open config file
@4000000064e633c103f86d14 INFO:device_service:Registering service pvinverter for client cb002 at path com.victronenergy.pvinverter.mqtt_cb002_Growatt
@4000000064e633c1066b9bac INFO:settingsdevice:Setting /Settings/Devices/mqtt_cb002_Growatt/ClassAndVrmInstance does not exist yet or must be adjusted
@4000000064e633c10a9c741c INFO:vedbus:registered ourselves on D-Bus as com.victronenergy.pvinverter.mqtt_cb002_Growatt
@4000000064e633c10b214804 INFO:device_service:Registered Service com.victronenergy.pvinverter.mqtt_cb002_Growatt under DeviceInstance 1
@4000000064e633c10b5e0ab4 INFO:device_manager:publish {'portalId': 'XXXXXXXXXX', 'deviceInstance': {'Growatt': '1'}} to device/cb002/DBus, status is 0
@4000000064e634080aae3314 *** CCGX booted (0) ***
@4000000064e6341c0dc90f74 *** starting dbus-mqtt-devices ***
@4000000064e6342f13929ccc -------- dbus_mqtt_devices, v0.5.1 is starting up --------
@4000000064e6342f1392b824 INFO:logger:Loglevel set to INFO
@4000000064e63431358c6984 INFO:device_manager:Using portalId XXXXXXXXXX
@4000000064e6343737830964 INFO:mqtt_gobject_bridge:[Init] Connecting to local broker
@4000000064e634380474116c INFO:device_manager:[Connected] Result code 0
@4000000064e6437322239214 INFO:device_manager:Received device status message {'clientId': 'fe001', 'connected': 1, 'version': 'v1.0 ALPHA', 'services': {'t1': 'temperature'}}
@4000000064e64373224a5fac INFO:device:**** Registering device: fe001, services: {'t1': 'temperature'} ****
@4000000064e643732252bc4c INFO:device:Registering Service temperature for client fe001
@4000000064e64373225f2fcc INFO:device_service_config:About to open config file
@4000000064e643740ebb9564 INFO:device_service:Registering service temperature for client fe001 at path com.victronenergy.temperature.mqtt_fe001_t1
@4000000064e6437410f6fabc INFO:settingsdevice:Setting /Settings/Devices/mqtt_fe001_t1/ClassAndVrmInstance does not exist yet or must be adjusted
@4000000064e6437414ff639c INFO:vedbus:registered ourselves on D-Bus as com.victronenergy.temperature.mqtt_fe001_t1
@4000000064e6437415557e94 INFO:device_service:Registered Service com.victronenergy.temperature.mqtt_fe001_t1 under DeviceInstance 1
@4000000064e643741583f134 INFO:device_manager:publish {'portalId': 'XXXXXXXXXX', 'deviceInstance': {'t1': '1'}} to device/fe001/DBus, status is 0
@4000000064e65183237d4614 INFO:device_manager:Received device status message {'clientId': 'fe001', 'connected': 1, 'version': 'v1.0 ALPHA', 'services': {'t1': 'temperature'}}
@4000000064e6518323a18f24 INFO:device_manager:publish {'portalId': 'XXXXXXXXXX', 'deviceInstance': {'t1': '1'}} to device/fe001/DBus, status is 0
`
I tried it at this moment. I only send 
`{"clientId":"cb002","connected":1,"version":"v1","services":{"Growatt":"pvinverter"}}`
and the position 1 to `W/X/pvinverter/1/Position`
At the moment no value is written so i inject a number and all is ok.
I don´t know what happened if the Inverter Produces. Is it possible that it updated too fast?

**Comment by freakent** [comment]
I couldn't say. The pvinverter config was created by the community so I have no experience with it. I can see from the log you are not having the problem with the YAML library that seems to be affecting many others. I don't see any errors in the log which is good. Perhaps someone else who uses pvinverter can chime in.

**Comment by Jacke87** [comment]
I wait until tomorrow. So when the sun is shining the values should be written. If it crashes i send the logfile. Is it a problem that my BMS which is connected via the Louis dB serial driver, has the same vrm instance number. Both have the 1?
Thanks for the support.

**Comment by freakent** [comment]
I don't know what the Louis dB serial driver is or how it works, and I don't know how you are registering your services on the dbus, so I can't offer advice. The deviceinstance id is only unique within the same service type, so if you are registering under 2 different service types then it would not surprise me if both have an Id of 1. If in doubt, use dbus-spy to inspect what values are actually in your dbus.

**Comment by freakent** [comment]
No updates for 3 weeks
