### ISSUE TITLE
Position move in Venus OS GUI

### ISSUE THREAD

**Issue by jeroenkl** [freakent/dbus-mqtt-devices#72]
Hi,

Any possibility to move the MQTT P1 grid and PV inverter from AC loads to the left side of the Multiplus device, 'next to grid-in'?

- [ ] 
![venus 9-11-2023](https://github.com/freakent/dbus-mqtt-devices/assets/37976568/5d5000f3-9e3b-4c92-99ba-5e187d947baa)
![Venus ](https://github.com/freakent/dbus-mqtt-devices/assets/37976568/be8d467b-5aa0-4875-a97d-51bade052272)

**Comment by freakent** [comment]
Not related to this project.
