### ISSUE TITLE
AC loads to position 0 instead of 1 in Venus OS GUI

### ISSUE THREAD

**Issue by jeroenkl** [freakent/dbus-mqtt-devices#73]
Hi,

Any possibility to move the MQTT P1 grid and PV inverter from AC loads to the left side of the Multiplus device, 'next to grid-in'?
/Position              <- 0=AC input 1; 1=AC output; 2=AC input 2

![Venus ](https://github.com/freakent/dbus-mqtt-devices/assets/37976568/4a376576-00d8-44e8-951f-338c9fc63e41)
![venus 9-11-2023](https://github.com/freakent/dbus-mqtt-devices/assets/37976568/e488ea19-bd5c-4d3b-961e-d410067797f4)

**Comment by freakent** [comment]
Not related to this project. Please take care which projects you raise issues against.
