### ISSUE TITLE
Inverter is not showing Values in VRM

### ISSUE THREAD

**Issue by KallerTobias** [freakent/dbus-mqtt-devices#76]
Hello, I have installed ad set up according to your manual. 
I get the IDs and I can write the values to MQTT (showing up in MQTT Explorer" but VenusOS is not showing the values. 

I currently do not have the inverter speaking to MQTT, the hardware will arrive in a few days, but I have a virtual output I'm writing to MQTT.
I double checked all topics etc. I can't find the problem.

Thank you,

Tobias

![Values are missing](https://github.com/freakent/dbus-mqtt-devices/assets/32508299/7effa958-8929-453f-ae59-af4eba995811)
![1](https://github.com/freakent/dbus-mqtt-devices/assets/32508299/b3f46d5e-0913-48b5-8915-43ad8f855c6c)
![Screenshot 2023-12-21 132848](https://github.com/freakent/dbus-mqtt-devices/assets/32508299/30dc8990-e041-4355-8708-227ff6e0772d)

**Comment by stundenblume** [comment]
Hi Tobias,
maybe try less values for the beginning.
this is how my pvinverter looks like.
![grafik](https://github.com/freakent/dbus-mqtt-devices/assets/1537231/f1cfd928-86aa-4438-89f9-869b1ce0bbc7)
Sebastian

**Comment by KallerTobias** [comment]
Hi Sebastian,

thank you for the reply. I now only transfered the Power for L3 and Total, still the same picture:
<img width="229" alt="Bildschirmfoto 2023-12-21 um 22 05 28" src="https://github.com/freakent/dbus-mqtt-devices/assets/32508299/842a9f79-c0ab-48e1-a407-9766c922bb13">
<img width="514" alt="Bildschirmfoto 2023-12-21 um 22 06 43" src="https://github.com/freakent/dbus-mqtt-devices/assets/32508299/1a6a9c22-b31a-4489-b6f9-0df7355facda">

The Topic, starting with "W" is correct, right?

**Comment by KallerTobias** [comment]
I will setup a clean system tomorrow, somethin is really strange there. I get the ID "2" for the PV Inverter, but when I analyse the N/.../pvinverter/ Topic I can see that the ID is 0. If I change the ID in my MQTT script, I can write at least the power, but no other Values. Also the MQTT server is breaking down constantly... I think I messed up something.

**Comment by freakent** [comment]
Tobias, please share your code you are using to register and send data values.

**Comment by KallerTobias** [comment]
HI, 
I send 
`{"clientId":"iv001","connected":1,"version":"v1.0","services":{"i1":"pvinverter"}}`
To the Topic: device/iv001/Status
I Recieved:
`{"portalId":"bxxxxxxxxxxf","deviceInstance":{"i1":"2"}}`

Data I transffered to Venus OS MQTT are e.g.:

Topic:
W/bxxxxxxxxxxf/pvinverter/2/Ac/Energy/Forward
`{"value":0.4}`
or
Topic:
W/bxxxxxxxxxxf/pvinverter/2/Ac/L3/Power
`{"value":460}`

Kind regards, 

Tobias

**Comment by halve85** [comment]
which Venus Version you're using?
Release candidate? (had the same issue with that - it's caused due to "dbus MQTT" not supported in future anymore, there will be an alternative.)

**Comment by freakent** [comment]
@halve, please do not leave comments like this. It is misleading to people new to Victron MQTT.  It is true that Victron have migrated off Mosquitto, but they have moved to FlashMQ and they functionality is mostly the same.

**Comment by freakent** [comment]
@KallerTobias It looks like the driver is working for you and registering your device. 

Can I suggest for test purposes you try setting up a dummy temperature sensor? It's possibly the simplest and will check your set up.

**Comment by disaster123** [comment]
> which Venus Version you're using? Release candidate? (had the same issue with that - it's caused due to "dbus MQTT" not supported in future anymore, there will be an alternative.)

This is just wrong. Victron supports mqtt like before. They‘re just using a different software / service.

**Comment by KallerTobias** [comment]
> @KallerTobias It looks like the driver is working for you and registering your device. 
> 
> Can I suggest for test purposes you try setting up a dummy temperature sensor? It's possibly the simplest and will check your set up. 

Hi,
Thanks for the support but I switched to a Shelly as EM and the Integrations works much better than the all possible SolaX solutions.
4 years ago when I bought this inverter, I was not aware of the closed system. 
The shelly integration works perfekt.
