### ISSUE TITLE
How to remove a device?

### ISSUE THREAD

**Issue by stundenblume** [freakent/dbus-mqtt-devices#8]
How can I remove a device?
Is that even necessary? 

While testing I created a lot of different devices. Now I have some unused device instances. Should they be released or doesn't that matter?

**Comment by freakent** [comment]
If you go into the regular venus console, there should be an option at the bottom of the menu saying "Remove disconnected devices", that will partially clean things up. Unfortunately the persisted settings are permanent - that's just how Venus uses dbus. Only thing to do is create a clean install of Venus.
![B58F4102-A57A-404E-8E9B-EF899B764CFC_1_102_o](https://user-images.githubusercontent.com/124850/161239733-d07037d8-30f8-4bc4-a55a-e66529cf07e6.jpeg)

**Comment by stundenblume** [comment]
OK, thank you. I don't have that entry.
But doesn't matter. I Don't plan to have that much unused sensors on the production system.

![grafik](https://user-images.githubusercontent.com/1537231/161335435-bb20290e-0d58-4f6e-8a31-8097c2dbd9e2.png)
